
package com.samples.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrderServices", targetNamespace = "http://com/samples/webservices/purchaseorderservice", wsdlLocation = "http://localhost:8080/ws/PurchaseOrderService.wsdl")
public class PurchaseOrderServices
    extends Service
{

    private final static URL PURCHASEORDERSERVICES_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERSERVICES_EXCEPTION;
    private final static QName PURCHASEORDERSERVICES_QNAME = new QName("http://com/samples/webservices/purchaseorderservice", "PurchaseOrderServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/PurchaseOrderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERSERVICES_WSDL_LOCATION = url;
        PURCHASEORDERSERVICES_EXCEPTION = e;
    }

    public PurchaseOrderServices() {
        super(__getWsdlLocation(), PURCHASEORDERSERVICES_QNAME);
    }

    public PurchaseOrderServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERSERVICES_QNAME, features);
    }

    public PurchaseOrderServices(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERSERVICES_QNAME);
    }

    public PurchaseOrderServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERSERVICES_QNAME, features);
    }

    public PurchaseOrderServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderService
     */
    @WebEndpoint(name = "PurchaseOrderServiceSoap11")
    public PurchaseOrderService getPurchaseOrderServiceSoap11() {
        return super.getPort(new QName("http://com/samples/webservices/purchaseorderservice", "PurchaseOrderServiceSoap11"), PurchaseOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderService
     */
    @WebEndpoint(name = "PurchaseOrderServiceSoap11")
    public PurchaseOrderService getPurchaseOrderServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/samples/webservices/purchaseorderservice", "PurchaseOrderServiceSoap11"), PurchaseOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERSERVICES_EXCEPTION!= null) {
            throw PURCHASEORDERSERVICES_EXCEPTION;
        }
        return PURCHASEORDERSERVICES_WSDL_LOCATION;
    }

}
