
package com.samples.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrderService", targetNamespace = "http://com/samples/webservices/purchaseorderservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrderService {


    /**
     * 
     * @param purchaseOrderRequest
     * @return
     *     returns com.samples.ws.PurchaseOrderResponse
     */
    @WebMethod(operationName = "PurchaseOrder")
    @WebResult(name = "PurchaseOrderResponse", targetNamespace = "http://com/samples/webservices/purchaseorderservice", partName = "PurchaseOrderResponse")
    public PurchaseOrderResponse purchaseOrder(
        @WebParam(name = "PurchaseOrderRequest", targetNamespace = "http://com/samples/webservices/purchaseorderservice", partName = "PurchaseOrderRequest")
        PurchaseOrderRequest purchaseOrderRequest);

}
