//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 11:49:26 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purchaseorder.webservices.samples.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.samples.webservices.purchaseorder;
